---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.6
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Write a Data Science Blog Post
### War for talent! What companies need to do to  attract talent within software engineering. 


With the help of the Stack Overflow Developer Survey from 2019 I want to answer the question, what companies need to do to attract talent within software engineering.
For the analysis of the data set I will follwo the CRISP-DM Process (Cross Industry Process for Data Mining)


### 1. Business Understanding


With the help of the Stack Overflow Developer Survey from 2019 I want to answer the question, what companies need to do to attract talent within software engineering.

War for talent! How companies need attract talent! 
When I worked in start up. The most challenages we face was to find software..
Base on study, there will be a shortage of software.. (50.00 by 2020)
In this ongogin war for talent, what must a company do to attract talent? 
How does programmer think? Whats important to them? Non it hr , manager, decision maker must undertand these people in order to attract them? Audience are HR and recruiting!

How must a company be to attract good programmer? 
What correlates most with the satisfied emlpoyess?
Do they program in their freetime? Space for own projects at work?
What size do the companies with satisfied emplpyees ah?
How big of a role plays the salary?
Working remote, more happy?

What are the most important factors for jobs satisfaction, and then have a closer look at them

Call for action for HR and companies!





### 2. Data Understanding

```{python}
# importing the neccessary libaries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
```

### Loading the data -  2019 Stack Overflow Developer Survey.


The data set is the full, cleaned results of the **2019 Stack Overflow Developer Survey**. Free response submissions and personally identifying information have been removed from the results to protect the privacy of respondents. There are two CSV files:


1. survey_results_public.csv - CSV file with main survey results, one respondent per row and one column per answer
2. survey_results_schema.csv - CSV file with survey schema, i.e., the questions that correspond to each column name

```{python}
# loading the dataset and the survey schema to the notebook
survey_schmema = pd.read_csv('survey_results_schema.csv')
survey_df = pd.read_csv('survey_results_public.csv')
survey_df.head()
```

```{python}
survey_schmema[survey_schmema['Column']=='CodeRevHrs']
```

```{python}
survey_schmema
```

```{python}
#gettinga first overview about the data
survey_df.shape
```

```{python}
survey_df.info()
```

Now take a look at the summary statistics associated with the quantitative variables in your dataset. 

```{python}
survey_df.describe()
```

We can also see from the summary statistics that we have missing values

```{python}
survey_df.hist();
```

One can see that the age, hours spend on code revies (CodeRevHrs) and the Salary (CompTotal, ConvertedCommp) are right-skweded

```{python}
# creating a heatmap to see correlations between the quantitative variables
sns.heatmap(survey_df.corr(), annot=True, fmt=".2f");
```

We can see the highest positive correlation between the compensations (Salary) and the Age, while the hours worked per week just seem to have weak correlation with the Salary


#### What are the factors that influence Job and career satisfaction the most (CareerSat & JobSat)?

```{python}
#lets have a look at the two variables CareerSat & JobSat
job_sat = survey_df.CareerSat.value_counts()
carrer_sat = survey_df.CareerSat.value_counts()
```

```{python}
#bar chart of the proportion of individuals in each category (from very satisfied to very dissatisfied) 
(job_sat/survey_df.shape[0]*100).plot(kind='bar')
plt.title('Proportion (%) Job satisfaction');
```

```{python}
#bar chart of the proportion of individuals in each category (from very satisfied to very dissatisfied) 
(carrer_sat/survey_df.shape[0]*100).plot(kind='bar')
plt.title('Proportion (%) Carrer satisfaction');
```

From the first overview we can see that we are dealing with a fairly high amount of missing values. So lets have a closer look the missing values

```{python}
# set of columns that doesnt have missing values
no_missing_values = set(survey_df.columns[survey_df.isnull().mean()==0])
print('Just the following columns have no missing values: {}'.format(no_missing_values))
```

```{python}
# lets have look at which coloums have the highest amount of missing data
survey_df.isnull().mean().sort_values(ascending=False)[:30]
```

```{python}
# lets have a look at the columns that have more than 20% missing values
over_20 = (survey_df.columns[survey_df.isnull().mean() > .2]).value_counts().sum()
print('{} % of the columns ({} columns) have more than 20% missing values'.format(((over_20/survey_df.shape[1]* 100)).round(2), over_20))
```

### 3. Prepare Data


### 4. Data Modeling


### 5. Evaluate the Results


### 6. Deploy

```{python}

```
